version: '3.8'

services:
  basket-api:
    container_name: basket-api
    restart: always
    build: .
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BINANCE_API_ENDPOINT=${BINANCE_API_ENDPOINT}
      - ONEINCH_API_ENDPOINT=${ONEINCH_API_ENDPOINT}
      - ONEINCH_API_KEY=${ONEINCH_API_KEY}
      - CHAIN_ICON_TEMPLATE_URL=${CHAIN_ICON_TEMPLATE_URL}
      - AVAILABLE_CHAIN_IDS=${AVAILABLE_CHAIN_IDS}
      - DEFAULT_CHAIN_ID=${DEFAULT_CHAIN_ID}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PARA_API_KEY=${PARA_API_KEY}

    network_mode: host