name: DEPLOY_PRODUCTION

on:
  push:
    branches: [production]

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main

      - name: Create .env file
        run: |
          cat << EOF > .env
          NODE_ENV=${{secrets.NODE_ENV}}
          DATABASE_URL=${{secrets.DATABASE_URL}}
          AUTH_SECRET=${{secrets.AUTH_SECRET}}
          TELEGRAM_BOT_TOKEN=${{secrets.TELEGRAM_BOT_TOKEN}}
          PRIVY_APP_ID=${{secrets.PRIVY_APP_ID}}
          PRIVY_APP_SECRET=${{secrets.PRIVY_APP_SECRET}}
          CDP_API_KEY_NAME=${{secrets.CDP_API_KEY_NAME}}
          CDP_API_KEY_PRIVATE_KEY=${{secrets.CDP_API_KEY_PRIVATE_KEY}}
          CDP_SK_ENCRYPTION_KEY=${{secrets.CDP_SK_ENCRYPTION_KEY}}
          OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}
          ONEINCH_API_KEY=${{secrets.ONEINCH_API_KEY}}
          BINANCE_API_ENDPOINT=${{secrets.BINANCE_API_ENDPOINT}}
          ONEINCH_API_ENDPOINT=${{secrets.ONEINCH_API_ENDPOINT}}
          CHAIN_ICON_TEMPLATE_URL=${{secrets.CHAIN_ICON_TEMPLATE_URL}}
          AVAILABLE_CHAIN_IDS=${{secrets.AVAILABLE_CHAIN_IDS}}
          AVAILABLE_TOKENS=${{secrets.AVAILABLE_TOKENS}}
          DEFAULT_CHAIN_ID=${{secrets.DEFAULT_CHAIN_ID}}
          REDIS_HOST=${{secrets.REDIS_HOST}}
          REDIS_PORT=${{secrets.REDIS_PORT}}
          REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}}
          BASE_RPC_URL=${{secrets.BASE_RPC_URL}}
          EOF

      - name: Run Docker Compose
        run: docker compose up -d --no-deps --build --remove-orphans

      - name: Run Docker System Prune
        run: docker system prune -f
